name: glados
version: 0.2.1

dependencies:
  - base >= 4.7 && < 5

ghc-options:
  - -Wall
  - -Wcompat
  - -Widentities
  - -Wincomplete-record-updates
  - -Wincomplete-uni-patterns
  - -Wmissing-export-lists
  - -Wmissing-home-modules
  - -Wpartial-fields
  - -Wredundant-constraints

library:
  source-dirs:
    - src
    - src/vm
    - src/strain
    - src/compiler
    - src/interpreter
  dependencies:
    - haskeline
    - bytestring
    - binary

executables:
  glados-exe:
    main: Main.hs
    source-dirs: app
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - glados
      - directory

tests:
  glados-test:
    main: UnitTests.hs
    source-dirs: 
      - test/unit_tests
      - test/unit_tests/strain_tests
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - glados
      - HUnit
