##
## EPITECH PROJECT, 2023
## GLaDOS
## File description:
## Makefile
##

all:
	@make -C ./code_generator

clean:
	@make clean -C ./code_generator

fclean:
	@make fclean -C ./code_generator

re: fclean all
