name: Haskell CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

permissions: write-all

jobs:
  build:   
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up GHC
        uses: haskell-actions/setup@v2

      - name: Build
        run: make release

      - name: Update and retrieve package version
        id: tag
        if: ${{ github.ref == 'refs/heads/main' }}
        run: |
          current_version="$(awk '/^version:/{print $2}' package.yaml)"
          new_version=$(echo $current_version | awk -F'.' '{print $1"."$2"."$3 + 1}')
          sed -i "s/^version: $current_version/version: $new_version/" package.yaml
          package_version="$(awk '/^version:/{print $2}' package.yaml)"
          echo "Package version is $package_version"
          echo "tag=$package_version" >> $GITHUB_OUTPUT
      
      - name: Create artifact
        run: |
          package_version="$(awk '/^version:/{print $2}' package.yaml)"
          tar -czvf "glados-v$package_version.tar.gz" .stack-work/install

      - name: Create release
        if: ${{ github.ref == 'refs/heads/main' }}
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ steps.tag.outputs.tag }}
          files: |
            glados-v${{ steps.tag.outputs.tag }}

      #- name: Run tests
        #run: make tests_run
